name: Build and Deploy
on:
  push:
    branches: [ gh-pages ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build React app
        run: npm run build
        
      - name: Replace GA Measurement ID in built files
        run: |
          find dist -name "*.html" -type f -exec sed -i "s/GA_MEASUREMENT_ID/${{ secrets.GA_MEASUREMENT_ID }}/g" {} \;
          
      - name: Deploy built files
        run: |
          # Remove source files and keep only dist contents
          find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.' -exec rm -rf {} +
          mv dist/* .
          rmdir dist
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Deploy built React app" || exit 0
          git push